package com.example.android.sqlconnect;

public class MovieModel {

    private int id;
    private String name;
    private int yearOfRelease;
    private String actor;
    private String actress;

    public MovieModel(int id, String name, int yearOfRelease, String actor, String actress) {
        this.id = id;
        this.name = name;
        this.yearOfRelease = yearOfRelease;
        this.actor = actor;
        this.actress = actress;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getYearOfRelease() {
        return yearOfRelease;
    }

    public void setYearOfRelease(int yearOfRelease) {
        this.yearOfRelease = yearOfRelease;
    }

    public String getActor() {
        return actor;
    }

    public void setActor(String actor) {
        this.actor = actor;
    }

    public String getActress() {
        return actress;
    }

    public void setActress(String actress) {
        this.actress = actress;
    }

    // tostring method is necessary to print all the messages together
//    It can be generated by alt+ insert and generate

    @Override
    public String toString() {
        return  id +
                "\nname: " + name +
                "\nYear Of Release: " + yearOfRelease +
                "\nActor: " + actor +
                "\nActress: " + actress;
    }
}
